---
- name: Ensure app dir exists
  file:
    path: /var/www/alvinespejo.com
    state: directory
    owner: www-data
    group: www-data

- name: Ensure web root exists
  file:
    path: /var/www/alvinespejo.com/public
    state: directory
    owner: www-data
    group: www-data

- name: Add PHP file
  copy:
    src: index.php
    dest: /var/www/alvinespejo.com/public/index.php
    owner: www-data
    group: www-data

- name: Remove default Nginx configurations
  command: rm -rf nginx/conf.d/.default.conf && rm -rf nginx/conf.d/no-ssl.default.conf
  args:
    chdir: /etc
  ignore_errors: yes

- name: Add Nginx configuration
  copy:
    src: alvinespejo.com.conf
    dest: /etc/nginx/conf.d/alvinespejo.com.conf
    owner: root
    group: root

- name: Reload Nginx
  service:
    name: nginx
    state: reloaded
